version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5432:5432"
  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    environment:
      - PG_HOST=db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      